In [18]:
import numpy as np 
import tensorflow as tf 
import tensorflow_datasets as tfds  

ds , ds_info = tfds.load("lfw", split="train", with_info=True, shuffle_files=False)


In [19]:
ds_info 

tfds.core.DatasetInfo(
    name='lfw',
    full_name='lfw/0.1.1',
    description="""
    Labeled Faces in the Wild: A Database for Studying Face Recognition in
    Unconstrained Environments
    """,
    homepage='http://vis-www.cs.umass.edu/lfw',
    data_dir='/Users/nandanprince/tensorflow_datasets/lfw/0.1.1',
    file_format=tfrecord,
    download_size=172.20 MiB,
    dataset_size=180.28 MiB,
    features=FeaturesDict({
        'image': Image(shape=(250, 250, 3), dtype=uint8),
        'label': Text(shape=(), dtype=string),
    }),
    supervised_keys=('label', 'image'),
    disable_shuffling=False,
    nondeterministic_order=False,
    splits={
        'train': <SplitInfo num_examples=13233, num_shards=2>,
    },
    citation="""@TechReport{LFWTech,
        author = {Gary B. Huang and Manu Ramesh and Tamara Berg and Erik Learned-Miller},
        title = {Labeled Faces in the Wild: A Database for Studying Face Recognition in Unconstrained Environments},
        institution = {Univer

In [20]:
ds 

<_PrefetchDataset element_spec={'image': TensorSpec(shape=(250, 250, 3), dtype=tf.uint8, name=None), 'label': TensorSpec(shape=(), dtype=tf.string, name=None)}>

In [21]:
ex = next(iter(ds))
print(ex["image"].shape)
print(ex["image"].dtype)
print(ex["image"].numpy().shape)
print(ex["image"].numpy().dtype)



(250, 250, 3)
<dtype: 'uint8'>
(250, 250, 3)
uint8


2026-02-24 19:07:09.821796: W tensorflow/core/kernels/data/cache_dataset_ops.cc:917] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [22]:
print(ex.keys())
print(ex["label"])
print(ex["image"].shape, ex["image"].dtype)

dict_keys(['image', 'label'])
tf.Tensor(b'Tom_Amstutz', shape=(), dtype=string)
(250, 250, 3) <dtype: 'uint8'>


In [23]:
ex["image"]

<tf.Tensor: shape=(250, 250, 3), dtype=uint8, numpy=
array([[[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       [[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       [[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       ...,

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 24,  22,  23],
        [ 23,  21,  22],
        [ 23,  21,  22]],

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 27,  25,  26],
        [ 25,  23,  24],
        [ 24,  22,  23]],

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 27,  25,  2

In [24]:
first = next(iter(ds))
print(type(first))
print(first["label"])
print(type(first["label"]))

<class 'dict'>
tf.Tensor(b'Tom_Amstutz', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>


2026-02-24 19:07:12.506921: W tensorflow/core/kernels/data/cache_dataset_ops.cc:917] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [25]:
print(first["image"].shape, first["image"].dtype)

(250, 250, 3) <dtype: 'uint8'>


In [26]:
first["image"]

<tf.Tensor: shape=(250, 250, 3), dtype=uint8, numpy=
array([[[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       [[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       [[207, 209, 195],
        [207, 209, 195],
        [208, 210, 196],
        ...,
        [215, 218, 201],
        [215, 218, 201],
        [215, 218, 201]],

       ...,

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 24,  22,  23],
        [ 23,  21,  22],
        [ 23,  21,  22]],

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 27,  25,  26],
        [ 25,  23,  24],
        [ 24,  22,  23]],

       [[ 30,  29,  25],
        [ 29,  28,  24],
        [ 29,  28,  24],
        ...,
        [ 27,  25,  2

In [27]:
#define a set to store unique identities
identities = set()
for example in ds:
    # print(example["label"])
    # identities.push(example["label"])
    identities.add(example["label"])
    # print(example["image"].shape, example["image"].dtype)
    # example["image"]
    # break
# print(len(identities))
    

2026-02-24 19:07:23.813108: W tensorflow/core/kernels/data/cache_dataset_ops.cc:917] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.